version: "3.9"
   
services:
  api:
    container_name: api
    build: 
      dockerfile: Dockerfile
      context: ./backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
      NODE_ENV: development
      PORT: 8000
    ports:
      - 8080:8000


  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - "35000:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db

  web:
    container_name: web
    stdin_open: true
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./frontend/
    volumes:
      - /app/node_modules # don't want to override node_modules
      - ./frontend:/app # live updates