version: "3.9"
   
services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - docker.env

  api:
    container_name: api
    build: 
      dockerfile: Dockerfile
      context: ./backend
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  web:
    container_name: web
    stdin_open: true
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./frontend/
    volumes:
      - /app/node_modules # don't want to override node_modules
      - ./frontend:/app # live updates

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    # volumes:
    #   - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
