version: "3.9"
   
services:
  db:
    container_name: db
    image: postgres:13
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  api:
    container_name: api
    build: 
      dockerfile: Dockerfile.dev
      context: ./backend
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "manage.py","runserver", "0.0.0.0:8000"]

  frontend:
    container_name: frontend 
    stdin_open: true
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/node_modules # don't want to override node_modules
      - ./frontend:/app # live updates

  nginx:
    container_name: nginx
    depends_on:
      - api
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'