version: '3'
services:
  db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@openbeats.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"
      - "5050:5050"